// Generated by CoffeeScript 2.0.0-alpha1
var Modal;

Modal = class Modal {
  constructor(headstr, bodystr, footstr) {
    var Remove;
    this.container = pen("div").Class("modal-container");
    this.head = pen("div").Class("modal-head");
    this.body = pen("div").Class("modal-body");
    this.foot = pen("div").Class("modal-foot");
    this.closebtn = pen("span").Class("close-button").Html("X");
    Remove = function(e) {
      pen(this.container).Remove();
      pen(this.closebtn).removeEventListener("click", Remove);
    };
    pen(this.closebtn).On("click", Remove);
    this.headText = pen("h2").Class("modal-head-text").Html(headerstr !== null ? headerstr : '');
    this.bodyText = pen("p").Class("modal-body-text").Html(bodystr !== null ? bodystr : '');
    this.footText = pen("h2").Class("modal-foot-text").Html(footstr !== null ? footstr : '');
    return this;
  }

  setHeadText(str) {
    pen(this.headText).Html(str);
    return this;
  }

  setBodyText(str) {
    pen(this.bodyText).Html(str);
    return this;
  }

  setFootText(str) {
    pen(this.footText).Html(str);
    return this;
  }

  Style(els, stroobj) {
    var el;
    if (pen.Type(el) === 'object') {
      for (el in els) {
        pen(this[el]).Css(els[el]);
      }
    } else {
      pen(this[el]).Css(stroobj);
    }
    return this;
  }

};
