// Generated by CoffeeScript 2.0.0-alpha1
(function(window, document) {
  var Start, body, contextmenu, dir, error, head, links, log;
  log = console.log, error = console.error, dir = console.dir;
  body = document.body, head = document.head;
  links = {};
  contextmenu = function(e) {
    var Remove, addLink, cntmnu, removeLink;
    e.preventDefault();
    cntmnu = pen("div").Css({
      left: `${e.clientX}px`,
      top: `${e.clientY}px`,
      position: "fixed",
      'z-index': 9999
    });
    Remove = function() {
      pen(cntmnu).Remove();
      pen(window).removeEventListener("click", Remove);
    };
    pen(cntmnu).AppendTo(body);
    pen(window).On("click", Remove);
    addLink = function(href, cover, ev) {
      links[cover] = {
        link: href,
        shownAs: cover,
        element: pen("a").Html(cover).Href(href),
        event: {
          type: ev.type != null ? ev.type : 'click',
          func: ev.func != null ? ev.func : function() {}
        }
      };
      pen(links[cover].element).On(links[cover].event.type, links[cover].event.func);
      pen(cntmnu).Append(links[cover].element);
    };
    removeLink = function(cover) {
      pen(links[cover].element).Remove();
      delete links[cover];
    };
    addLink("javascript:void 0;", "reload", {
      type: "click",
      func: function() {
        return location.reload();
      }
    });
    return cntmnu;
  };
  Start = function(e) {
    var closebtn, header, reloader, stylsheet, title;
    pen(window).On("contextmenu", contextmenu);
    header = pen("div").Class("header-title");
    title = pen("span").Class("title").Html(document.title);
    reloader = pen("span").Class("button-header Ril").Html("reload").On("click", (e) => {
      e.preventDefault();
      location.reload();
    });
    closebtn = pen("span").Class("button-header Ril").Html("X").On("click", (e) => {
      e.preventDefault();
      close();
    });
    stylsheet = pen("style").Html(".Ril {float:right} .Lil {float:left}");
    pen(head).Append(stylsheet);
    pen(header).Append(title, closebtn, reloader).AppendTo(body);
    return log(`Loading took ${Math.round(e.timeStamp)} second(s)`);
  };
  return window.onload = Start;
})(window, document);
