// Generated by CoffeeScript 2.0.0-alpha1
var HyperButton, body, head;

body = document.body;

head = document.head;

HyperButton = (function() {
  class HyperButton extends HTMLElement {
    constructor() {
      super();
      this.name = '';
      this.href = '#';
      this.cover = '';
      pen(this).On('click', this.goTo);
    }

    static checkString(string) {
      if (string.match(/\s+/)) {
        string = string.replace(/\s+/, '-');
      }
      return string;
    }

    goTo(e) {
      pen(this).Html(`relocating to ${this.cover}...`);
      window.location = this.href;
      return void 0;
    }

  };

  get(href()(function() {
    return this.getAttribute('href');
  }));

  set(href(str)(function() {
    var str;
    str = HyperButton.checkString(str);
    return this.setAttribute('href', str);
  }));

  return HyperButton;

})();

customElements.define('dav-com', HyperButton);
